Update: gdextension
Removing editor targets as they don't seem to affect anything and it appears to be causing errors when trying to export for CI builds. See previous macos jobs when exporting for template release:
ERROR: Can't open dynamic library: /Users/runner/work/godot-cpp-template/godot-cpp-template/game/bin/./macos/libgame.macos.editor.dylib

Some cleaning export script too.